package com.danrus.bb4j;

import com.danrus.bb4j.api.BbModel;
import com.danrus.bb4j.api.CompressionMode;
import com.danrus.bb4j.api.ReadOptions;
import com.danrus.bb4j.api.WriteOptions;
import com.danrus.bb4j.io.LzUtf8Codec;
import com.danrus.bb4j.model.BbModelDocument;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Verifies bb4j's LZUTF8 codec is compatible with Blockbench's compressed
 * {@code .bbmodel} format.
 *
 * <p>The decoder is checked against a real Blockbench-produced compressed file
 * ({@code java_block_my_axe.blockbench.lz}, generated by running the reference
 * {@code lzutf8.js} with {@code StorageBinaryString} output), and the codec is
 * checked for self-consistent round-tripping.
 */
class CompressionTest {

    private static String loadResource(String path) throws IOException {
        try (InputStream in = CompressionTest.class.getResourceAsStream(path)) {
            assertNotNull(in, "Missing resource: " + path);
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    @Test
    void decompressesRealBlockbenchOutput() throws IOException {
        String original = loadResource("/models/java_block_my_axe.bbmodel");
        String compressed = loadResource("/models/java_block_my_axe.blockbench.lz");

        assertTrue(compressed.startsWith("<lz>"), "Reference file should be LZ-compressed");

        String decompressed = LzUtf8Codec.decompress(compressed);
        assertEquals(original, decompressed,
                "Decompressing Blockbench's output must reproduce the original JSON exactly");
    }

    @Test
    void documentReadFromBlockbenchCompressedFileMatchesPlain() throws IOException {
        String plain = loadResource("/models/java_block_my_axe.bbmodel");
        String compressed = loadResource("/models/java_block_my_axe.blockbench.lz");

        // AUTO mode must detect and transparently decompress the <lz> payload.
        BbModelDocument fromPlain = BbModel.read(plain);
        BbModelDocument fromCompressed = BbModel.read(compressed);

        assertEquals(BbModel.write(fromPlain), BbModel.write(fromCompressed),
                "A model read from a compressed file must equal the same model read from plain JSON");
    }

    @Test
    void codecRoundTripsArbitraryContent() {
        String[] samples = {
                "{}",
                "{\"meta\":{\"format_version\":\"5.0\"},\"name\":\"тест юникод ☃\"}",
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", // highly repetitive
                "The quick brown fox jumps over the lazy dog. ".repeat(200)
        };
        for (String sample : samples) {
            String compressed = LzUtf8Codec.compress(sample);
            assertTrue(compressed.startsWith("<lz>"));
            assertEquals(sample, LzUtf8Codec.decompress(compressed),
                    "compress -> decompress must be lossless");
        }
    }

    @Test
    void writeCompressedThenReadRoundTrips() throws IOException {
        String original = loadResource("/models/geckolib_animations.bbmodel");
        BbModelDocument doc = BbModel.read(original);

        WriteOptions compressed = WriteOptions.builder().compressionMode(CompressionMode.LZUTF8);
        String out = BbModel.write(doc, compressed);
        assertTrue(out.startsWith("<lz>"), "LZUTF8 write mode must emit a compressed payload");

        BbModelDocument reread = BbModel.read(out, ReadOptions.builder());
        assertEquals(BbModel.write(doc), BbModel.write(reread),
                "A compressed write must round-trip back to the same document");
    }
}
